name = "nft-ai-app"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"



[vars]
CLOUDFLARE_ACCOUNT_ID = "dc56444c4c955a1653106ccf997c1067"