name = "nft-ai-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "nft-ai-app"
binding = "BUCKET"

[vars]
CLOUDFLARE_ACCOUNT_ID = "dc56444c4c955a1653106ccf997c1067"