[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_gifter = "5PvnABfeQoqHGGGQ87BmjPCJ41wBuiSu3L3h4RbH4Zj1"

[programs.devnet]
nft_gifter = "5PvnABfeQoqHGGGQ87BmjPCJ41wBuiSu3L3h4RbH4Zj1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**.*.ts"
init-config = "npx ts-node scripts/init_config.ts"
create-mint = "npx ts-node scripts/create-mint.ts"
show-config = "npx ts-node scripts/show_config.ts"
update-config = "npx ts-node scripts/update_config.ts"
