[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_gifter = "5gm1Nn7N3BDn2og4Umw5JePUhLUF2azKqwJduQx3tApg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**.*.ts"
init-config = "npx ts-node scripts/init_config.ts"
show-config = "npx ts-node scripts/show_config.ts"
update-config = "npx ts-node scripts/update_config.ts"
